# Generated by Django 6.0.2 on 2026-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(default='aaaaaaaaaaaaaaaaaaaa', max_length=20, primary_key=True, serialize=False),
        ),
    ]
