# Generated by Django 6.0.2 on 2026-02-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_id_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='number',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
