# Generated by Django 6.0.2 on 2026-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_account_number_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
